import { db } from "../server/db";
import { hospitalServiceDepartments, hospitalServices } from "../shared/schema";
import { eq } from "drizzle-orm";

async function seedServicesBatch4() {
  console.log("Starting batch 4 services seeding...");

  const newDepartments = [
    { slug: "uro-surgery", name: "URO Surgery", description: "Urological surgical procedures", iconKey: "Stethoscope", displayOrder: 20 },
    { slug: "pathology", name: "Pathology", description: "Laboratory diagnostics and pathology tests", iconKey: "FlaskConical", displayOrder: 21 },
    { slug: "radiology", name: "Radiology", description: "Imaging and diagnostic radiology services", iconKey: "ScanLine", displayOrder: 22 },
    { slug: "rehab-services", name: "Rehab Services", description: "Rehabilitation and physiotherapy services", iconKey: "Accessibility", displayOrder: 23 },
    { slug: "gastroenterology", name: "Gastroenterology", description: "Gastroenterology procedures and endoscopy", iconKey: "CircleDot", displayOrder: 24 }
  ];

  const uroSurgeryServices = [
    "BLADDER CLOT EVACUATION WITH SEPGARD INSTILLATION LEVEL-1", "CIRCUMCISION (LA) LEVEL 1", "CYSTOSCOPY -LEVEL 1", "DIAGNOSTIC CYSTOSCOPY (LA) LEVEL-1",
    "FRENULECTOMY LEVEL-1", "INSERTION OF DJ STENT LA LEVEL1", "MEATOTOMY (URETHRAL) LEVEL-1", "NEPHROSTOMY CHANGE UNDER C-ARM CONTROL LEVEL-1",
    "NEPHROSTOMY INSERTION (LEVEL 1)", "PENILE BIOPSY LEVEL-1", "REMOVAL OF DJ STENT-LEVEL 1", "TESTICULAR / SCROTAL BIOPSY UNDER ANAESTHESIA LEVEL 1",
    "TRU-CUT BIOPSY OF PROSTATE LEVEL-1", "URETHRAL DILATION LEVEL1A", "URO-SURG. LEVEL-1", "VASOGRAPHY LEVEL 1",
    "CHECK NEPHROSCOPY LEVEL 2", "CIRCUMCISION/MEATOTOMY UNDER ANAESTHESIA(G.A) LEVEL2", "CYSTOSCOPY BLADDER BIOPSY (OT) - LEVEL 2",
    "CYSTOSCOPY WITH CLOT EVACUATION LEVEL-2", "CYSTOSCOPY WITH URETRAL DIALATION - LEVEL 2", "CYTOSCOPY & SUPRAPUBICSCOPY WITH BOUGIOGRAM-LEVEL 2",
    "INSERTION OF DJ STENT GA LEVEL 2", "NON SCALPEL VASECTOMY (NSV) LEVEL-2", "PCN LEVEL 2", "PROSTATE BIOPSY (GA) LEVEL 2",
    "RENAL CYST ASPIRATION (USG GUIDED) - LEVEL 2", "RGP LEVEL 2", "SPC - LEVEL2", "URO-SURG. LEVEL-2", "VASECTOMY LEVEL2",
    "ANTEGRADE STENTING IN TRANSPLANT KIDNEY NEPHROSTOMY LEVEL-3", "CYSTOSCOPY WITH FULGURATION OF BLEEDING POINTS LEVEL-3",
    "CYSTOSCOPY WITH RGP & DJ STENTING LEVEL-3", "DIAGNOSTIC URETEROSCOPY - LEVEL 3", "EPIDIDYMAL CYCT (LARGE) EXCISION LEVEL-3",
    "HYDROCELE (UNILATERAL) URO LEVEL 3", "INTRA OPERATIVE CONSULTATION FOR BLADDER TEAR & CYSTOSCOPY LEVEL-3", "MEATOPLASTY LEVEL3",
    "OPEN BLADDER STONE SURGERY - LEVEL3", "SECOND STAGE PCNL - LEVEL3", "SMALL STONE BLADDER CYSTOLITHOTRIPSY - LEVEL3",
    "TESA / PESA - LEVEL3", "TRANSPLANT GRAFT STENTING LEVEL-3", "TUIP - LEVEL3", "UNILATERAL VARICOCELE LIGATION - LEVEL3",
    "URETEROCOELE INCISION LEVEL-3", "URO-SURG. LEVEL-3", "VIU( VISUAL INTERNAL URETHROTOMY) - LEVEL3",
    "BIG STONE BLADDER CYSTOLITHOTRIPSY - LEVEL4", "BILAT. DJ STENTING LEVEL-4", "BILATERAL VERICOCELE LIGATION - LEVEL4",
    "BLADDER DIVERTICULECTOMY - LEVEL4", "CORE THROUGH URETHROTOMY (LEVEL 4)", "CYSTOLITHOTRIPTY - LEVEL 4",
    "CYSTOSCOPY WITH BLADDER SUTURING -LEVEL 4", "CYSTOSCOPY WITH CLOT EVACUATION WITH FULGURATION OF BLLEDING POINT LEVEL-4",
    "CYSTOSCOPY WITH URS WITH DJ STENTING UNILATERAL LEVEL - 4", "DIAGNOSTIC - URS LEVEL-4", "HIGH ORCHIDECTOMY FOR TESTICULAR TUMOR LEVEL-4",
    "HYDROCELE (BILATERAL) URO LEVEL 4", "LAP VARICOCELE Sx - LEVEL4", "ORCHIDECTOMY UNILATERAL - LEVEL4", "ORCHIOPEXY UNILATERAL - LEVEL4",
    "PSOAS ABSCESS - DRAINAGE (OPEN) LEVEL - 4", "RENAL CYST EXCISION(OPEN) - LEVEL 4", "SCORTAL INCISION WITH DEBRIDEMENT WITH EXCISION OF SCROTAL SKIN (small) Level- 4",
    "TUR-BT GRADE A -LEVEL 4", "UNILATERAL INGUINAL LN DISSECTION - LEVEL4", "URETERIC DISSECTION AT MYOMECTOMY & CONTROL OF BLEEDING LEVEL-4", "URO-SURG. LEVEL-4",
    "BILATERAL INGUINAL LN DISSECTION - LEVEL5", "BILATERAL ORCHIDOPEXY - LEVEL5", "CLAM SHELL CYSTOPLASTY LEVEL5", "CROSS VVA - LEVEL5",
    "CYSTOSCOPY & URS WITH LITHOTRIPSY WITH STENTING LEVEL-5", "CYSTOSCOPY B/L.STENTING & PCN (LEVEL-5)", "EXPLORATION OF TRANSPLANT GRAFT & HAEMATOMA EVACUATION LEVEL -5",
    "FRACTURE PENIS LEVEL-5", "HILAR CLEARANCE FOR CHYLURIA - LEVEL5", "MICRO VEA - LEVEL5", "MICRO VVA - LEVEL5", "OPEN NEPHRECTOMY - LEVEL5",
    "ORCHIDECTOMY BILATERAL - LEVEL5", "ORCHIDECTOMY ONE SIDE & ORCHIOPEXY OPP. SIDE - FOR TORSION LEV-5", "PARTIAL CYCTECTOMY WITH LND (OPEN) LEVEL-5",
    "REDUCTION CYSTOPLASTY LEVEL5", "RENAL CYST EXCISION(Lap) - LEVEL5", "SUI SURGERY (SLINGS) TOT/TVT - LEVEL 5", "TUR-BT GRADE B - LEVEL5",
    "TURP - SINGLE SITTING SMALL - LEVEL5", "URACHUS EXCISION FOR CANCER (OPEN) LEVEL-5", "URETERIC RE-IMPLANTATION - LEVEL 5",
    "URETEROLITHOTOMY (OPEN) LEVEL-5", "URETEROSCOPY (LOWER URETER) - LEVEL5", "URETEROTOMY (OPEN) LEVEL-5", "URINARY DIVERSION GRADE A - LEVEL5",
    "URO-SURG. LEVEL-5", "URO-SURGERY LEVEL-5 ASSOCIATE SURGEON CHARGES",
    "BOARI - LEVEL6", "EXPLORATION WITH SUTURING OF BLADDER TEAR LEVEL-6", "FLEXIBLE URS URETER & KIDNEY STONE REMOVAL LEVEL-6",
    "HILAR CLEARANCE FOR CHYLURIA (LAP) - LEVEL6", "LAP ADRENALECTOMY - LEVEL6", "LAP. NEPHRECTOMY - LEVEL6", "LAPROSCOPIC URETEROTOMY LEVEL -7",
    "NEPHRO-URETERECTOMY - LEVEL6", "OPEN PROSTATECTOMY - LEVEL6", "OPEN PYELOPLASTY - LEVEL6", "PARTIAL PENECTOMY / TOTAL PENECTOMY (without LN dissection) - LEVEL6",
    "PCNL GRADE A - LEVEL6", "PYELOLITHOTOMY -LEVEL -6", "RIRS (RETROGRADE INTRA RENAL SURGERY) FOR SMALL STONE LEVEL-6A",
    "SCORTAL SKIN DEBRIDEMENT WITH EXCISION OF SKIN FOR FOURNIERS GANGRENE LEVEL- 6", "TURP - SINGLE SITTING BIG - LEVEL6",
    "URETEROSCOPY (UPPER URETER) - LEVEL6", "URETHROPLASTY GRADE A - LEVEL6", "URINARY DIVERSION GRADE B - LEVEL6", "URO-SURG. LEVEL-6",
    "URO-SURGERY LEVEL-6 ASSOCIATE SURGEON CHARGES", "URO-SURGERY LEVEL-6A ASSOCIATE SURGEON CHARGES", "VVF / VUF REPAIR - LEVEL6",
    "CYSTECTOMY OPEN - LEVEL7", "CYSTOSCOPY & RGL& EXP.LAP.FOR RUPTURE& CLOSURE OF BLADDER L-7", "EXPLORATORY LAPAROTOMY WITH NEPHRORRAPHY FOR RENAL TEAR LEVEL-7",
    "GRAFT RE-EXPLORATION & PYELO-VERICOSTOMY OF GRAFT LEVEL-7", "ILEAL CONDUIT (AFTER RADICAL CYSTECTOMY) LEVEL 7", "LAPAROSCOPIC PYELOPLASTY - LEVEL 7",
    "NEOBLADDER (AFTER RADICAL CYSTECTOMY) LEVEL 7", "PARTIAL CYSTECTOMY - LEVEL 7", "PCNL GRADE B - LEVEL7", "RADICAL NEPHRECTOMY OPEN - LEVEL7",
    "REVISION T.U.R.P LEVEL-7", "RIRS (RETROGRADE INTRA RENAL SURGERY) FOR BIG STONE LEVEL-7", "RIRS (RETROGRADE INTRA RENAL SURGERY) FOR TUMOUR LEVEL-7",
    "TOTAL PENECTOMY WITH NODE DISSECTION - LEVEL7", "TRANS URETERO-URETEROSTOMY - LEVEL7", "URETHRAL DISRUPTION WITH PELVIC FRACTURE & HAEMATOMA FOR RE-ALIGNMENT LEVEL-7",
    "URETHROPLASTY GRADE B - LEVEL7", "URO-SURG. LEVEL-7", "URO-SURGERY LEVEL-7 ASSOCIATE SURGEON CHARGES",
    "ANATROPHIC PARTIAL NEPHRECTOMY- LEVEL 8", "AUGMENTATION CYSTOPLASTY - LEVEL8", "CYSTECTOMY LAP. - LEVEL8",
    "EXPLORATION OF TRANSPLANT GRAFT WITH URETERO-URETRIC ANASTOMOSIS LEV-8", "ILEAL URETER - LEVEL8", "LAP PYELOPLASTY WITH PYELOLITOTOMY LEVEL-8",
    "LAP RETROPERITONEAL MASS EXISION - LEVEL8", "LAPROSCOPIC PARTIAL NEPHRECTOMY LEVEL-8", "NEPHRECTOMY FOR POLYCYSTIC KIDNEYS L-8",
    "NEPHROLITHOTOMY WITH DJ STENTING -LEVEL 8", "RADICAL CYSTECTOMY WITH ILEAL CONDUIT LEVEL 8", "RADICAL NEPHRECTOMY LAP. - LEVEL8",
    "RETROPERITONEAL MASS EXCISION LEVEL 8", "URETHROPLASTY GRADE C - LEVEL8", "URO-SURG. LEVEL-8", "URO-SURGERY LEVEL-8 ASSOCIATE SURGEON CHARGES",
    "EXPL.LAPRO. WITH ADHEOLYSIS & ILLEAL URETER WITH RA OF SMALL BOWEL-LEVEL 9", "OPEN KIDNEY STONE AND URETERIC STONE REMVOAL LEVEL-9",
    "RADICAL NEPHRECTOMY PLUS IVC THROMBECTOMY - LEVEL9", "RADICAL PROSTATECTOMY LAP. - LEVEL9", "RADICAL PROSTATECTOMY OPEN - LEVEL9",
    "URETROSCOPY & NEPHRORESCETOMY L-9", "URO-SURG. LEVEL-9", "URO-SURGERY LEVEL-9 ASSOCIATE SURGEON CHARGES",
    "Capd Surgical Removal (continuous Ambulatory Pertoneal Dia)"
  ];

  const pathologyServices = [
    "111 Conditions", "118 Conditions/119 Conditions", "4 Conditions", "5-HT (5-Hydroxy Tryptamine)", "7 Conditions",
    "A.C.E (Angiotensin Converting Enzyme)", "Abg-Lactate-Electrolyte Profile", "Acid Phophatase-Total Serum", "Acid Phosphatase With Prostatic Fraction",
    "ADA - Adenosine Deaminase", "Albumin", "Aldolase", "Aldosterone", "Alkaline Phosphatse With Bone Fraction", "Aluminium", "Ammonia", "Amylase",
    "Apo B", "Apo A1", "Arsenic (Blood)", "Arsenic (Urine)", "Arsenic Level (Scalp Hair)", "Arterial Blood Gas Analysis", "Arterial Blood Gas And Electrolytes",
    "Ascitic Fluid Routine", "Barbiturates (Urine)", "Bence Jonce Protein(24 hrs Urine)", "Bence Jones Proteins", "Benzodiazapine (Urine)", "Bicarbonate",
    "Bile Acid", "Blood pH", "Bone Profile", "BUN", "BUN (Pre HD)", "BUN (Post HD)", "Calcium (24 Hours Urine)", "Calcium (Random Urine)",
    "Cardiac Injury Profile", "Cardiac Risk Profile", "Catecholamine(Urine And Plasma)", "Catecholamines (Urine)", "Chloride", "Cholinesterase",
    "Chromosomal analysis for down syndrome", "Chylomicrons", "CITRATE ( URINE 24 HRS )", "Comprehensive myeloma protein panel",
    "Copper-24 Hours Urine -Atomic Absorption", "Cornary Risk Profile", "CPK- MB", "CPK( Serum Creatine Phosphokinase)", "C-Reactive Proteins (Quantitative)",
    "Creatinine", "Creatinine (Post HD)", "Creatinine (Pre HD)", "Creatinine Clearance Test(24hrs.)", "Creatinine(collection center)",
    "Cryoglobulin(Qualitative)", "CSF (Lactate)", "CSF Protein Electrophoresis/Oligoclonal Bands", "CSF Routine", "Cyclosporin A Peak Level (c2)",
    "Cyclosporin A Trough Level (co)", "D - Dimer", "Diabetic Profile", "Drug Of Abuse Panel - 5 Drug Panel Urine", "Drugs Of Abuse Profile(Quantitative) 9 Drugs Profile",
    "Electrolytes", "ELECTROLYTES (ABG)", "Eptoin/Phenytoin", "Extended Lipid Profile", "Extened Glucose Tolerance Test", "Fluid Albumin", "FLUID BILIRUBIN",
    "Fluid BUN", "Fluid Creatinine", "Fluid Protein", "Fluid Triglycerides", "Fructosamine", "Glucose Challenge Test(75 Gms Glucose)",
    "Glucose Tolerance Test (75gms - 3 Samples)", "HIAA (5-hydroxy Indole Acetic Acid)Urine 24hrs", "Homocystein Urine", "Homogentesic Acid",
    "Hypertension Profile", "Ionized Calcium", "Lactate", "LACTATE(ABG)", "LDH - Lactate Dehydrogenase", "LDL (Direct)", "Lead Level (Blood)",
    "Lead(Urine)", "LFT - Maxi (Liver Function Test)", "LFT - Mini (Liver Function Test)", "LFT- Liver Profile", "Lipid Profile", "Lipoprotein(A)",
    "Magnesium", "Mercury ( urine )", "Mercury(blood)", "Metabolic Disorder Study (GC/MS)(Urine)", "Metanephrines(Urine)", "Methionine",
    "Mucopolysaccharidosis(MPS) Spot Test", "Newborn Standard 11 Conditions", "NT-PRO BNP", "Oxalate (Oxalic Acid) 24 Hrs Urine", "Paracetamol(Acetaminophane)",
    "Plasma Free Metanephrines", "Plasma Amino Acids", "Plasma Free Nor Metanephrine (Metropolis)", "Plasma Free Nor Metanephrines (Hinduja)",
    "Plasma Glucose (Random)", "Plasma Glucose Fasting", "Plasma Glucose Fasting And Post Lunch Or P.Glucose(2s", "Plasma Glucose Post-Lunch",
    "Post Glucose Sugar", "Potassium", "Pre Procedure Creatinine", "Pre-Operative Cardiac Profile", "Pseudo Cholinesterase", "Pyruvic Acid",
    "Quantitative Amino Acid (Plasma)", "Renin Activity In Plasma(PRA)", "RFT- Renal Profile", "S.G.O.T.", "S.G.P.T.", "Serum Acetone/Ketone",
    "Serum Alcohol", "Serum ALKPO4", "Serum ascites albumin gradient (SAAG)", "Serum Bilirubin (Total Bilirubin& Direct Bilirubin)", "Serum Calcium",
    "Serum Cholesterol-Total", "Serum Gama GT", "Serum HDL Cholesterol", "Serum Homocystein", "Serum Inorg. Phosphorus", "Serum Iron",
    "Serum Iron & Total Iron Binding Capacity", "Serum Lipase", "Serum Lithium", "Serum Methotrexate Level", "Serum Osmolality", "Serum Proteins",
    "Serum Triglycerides", "SMA 12", "Sma 12+2", "Sodium", "Sodium Level In Breast Milk", "Stone Analysis", "Synovial Fluid", "TCO2",
    "Thallium Level (Urine)", "Thallium Level(Scalp Hair)", "Thallium(Blood Level)", "TMP/GFR", "TMS 52", "TMS 52 + 6", "TMS 52 + 6 + Hb",
    "TOXICITY MAXI PROFILE HEAVY METAL", "Toxin A Screening", "Toxin B Screening", "Troponin I", "Troponin T", "Urea", "Uric Acid",
    "Urinary Albumine/Creatinine Ratio", "Urinary Bicarbonate", "Urinary BUN", "Urinary Calcium /Creatinine Ratio", "Urinary Chloride",
    "Urinary Creatinine.", "Urinary Electrolytes", "Urinary Magnesium", "Urinary Magnesium(24 Hours)", "Urinary Myoglobin", "Urinary Phosphorus",
    "Urinary Potassium", "Urinary Protein.", "Urinary Sodium", "URINARY UREA", "Urinary Uric Acid", "Urinary Uric Acid/Creatinine Ratio",
    "Urine Chylomicron", "Urine Dysmorphic RBC", "Urine For Micral", "Urine Osmolality", "Urine Protein /Creatinine Ratio", "Vancomycin Level (Hinduja Hospital)",
    "Venous Blood Gas Analysis", "Venus Blood Gas with Electrolytes", "Venus Blood Gas with Electrolytes & Lactate", "Adam TS 13", "Bile Pigment",
    "Bile Salt", "Calprotectin", "CFH Ab", "Clotting time", "Fecal Fat", "Fluid Hct", "Fluid Routine", "Glass Test 1", "Glass Test 2", "Glass Test 3",
    "HLA Hypersensitivity to ABACAVIR (B.57:01)", "Immunodefeciency panel", "JAK2 Gene Analysis - 2 Exons (12 & 14)", "Mercury 24 Hrs", "Mercury Urine Spot",
    "Methyl Malonic Acid (qualitative)", "Methyl Malonic Acid (quantitative)", "Occult Blood Test(Stool)", "Occult Blood Test(Urine)",
    "PORPHOBILINOGEN (QUANTITATIVE)", "Porphobilinogen(Qualitative Screening)", "Porphyria Profile", "POSOCONAZOLE TROUGH LEVEL", "Pregnancy Test",
    "Rota Virus Detection ,stool", "Semen Analysis", "Sepsis Screening", "Serum Itraconazole (Trough) levels", "Stool for Cryptosporidium -Isospora- Microsporidium",
    "Stool For Reducing Substance", "Stool For Strongiloides", "STOOL PH", "Stool Routine", "Urinary Acetone(Qualitative)", "Urinary Albumin", "Urinary pH",
    "Urine For R.B.C.morphology", "Urine For Reducing Substances", "Urine Ketone (Qualitative)", "Urine Routine", "Urine Specific Gravity", "Urine Sugar",
    "Urobilinogen(Qualitative)", "Absolute Eosinophil Count", "Acquired Thrmbophilia Panel", "Acute Leukemia Comprehensive Reflex Panel - 1",
    "Acute Leukemia Comprehensive Reflex Panel - 2", "AML MRD", "Anaemia Profile (Maxi)", "Anti Thrombin III Activity", "APTT Inhibitor Screen(Mixing study)",
    "Band /Neutrophil Ratio", "Bleeding Time", "Blood Collection Charges(short Distance)", "Blood Microfilaria", "CBC ( Complete Blood Count )",
    "CBC With ESR", "CD34", "Coagulation Profile", "Cytogenetics Studies:Autogen DT 5102", "Cytogenetics:Phildelphia Chromosome(bcr)", "DIC Profile",
    "DIL Russel Vip Ven Time", "E.S.R.", "Eosinophil count", "Eosinophilia Panel", "Factor IX (Anti Haemophilic B) Actiivty", "Factor V (activity) -APCR",
    "Factor V Mutation Detection", "Factor VII", "Factor VIII", "Factor X (Stuart Power) Activity Plasma", "Factor Xa Antibody", "FACTOR XI",
    "Factor-XIII(13) Activity", "Fibrinogen", "Fibrinogen Degradation Products", "Flowcytometry Leukocyte Adhesion Deficiency", "Fluid Crystal",
    "Foetal Haemoglobin (HBF)", "G6 PD Qualitative", "G6PD Quantitative", "Glycosylated Hemoglobin(HBA1C)", "Haemoglobin-In Urine", "Haemolytic Anaemia Profile",
    "HB/PCV", "HEAMOPHILIA PROFILE", "Heinz Bodies", "Hemoglobin", "Hemoglobin Electrophoresis/HB Varient Analysis", "Heparine Induced Antidody",
    "Hereditary Thrombophilia Panel", "HLA (a B C)", "HLA (dr/dq)", "HLA B27", "HLA Cross Matching DSA Luminex", "HLA Cross Matching(recipient/donor)",
    "HLA Typing- Molecular Luminex(DQ Locus)", "HLA Typing Pcr/ssp(donor)", "HLA Typing Pcr/ssp(recipient)", "Immature Platelet Fraction",
    "Immunophenotyping Panel", "Kaolin Clotting Time (KCT)", "L.E.cells", "LAP-Score", "Lupus Anticoagulant Screening Profile", "Lymphocyte Cross CDC",
    "Lymphocyte Cross Matching (Live)", "Malarial Antigen", "Malarial Parasites", "Methaemoglobin", "Micro ESR", "MTHFR Gene Mutation",
    "Myeloperoxidase Staining (mpo) (Blood And Bone Marrow)", "New born screening (7 conditions)", "Osmotic Frgility Test (RBC Fragility Test)",
    "Peripheral Smear Study", "Plasma Haemoglobin", "Platelet Count", "Platelet Function Test (Hinduja Hospital)", "Platelet mapping on TEG",
    "PNH(CD55 And CD59)", "Porphyrins(24hrUrine)", "Porphyrins(Blood)", "Protein C (activity)", "Protein S (activity)", "Protein S antigen (free) plasma",
    "Prothrombin(Factor-II)mutation Detection", "PT - Prothrombin Time", "PT Mixing Study", "PTT - Partial Thromboplastin Time", "Reticulocytes",
    "Sample Transport Charges Outside MH Within India", "Sample Transportation Charges", "Sickling Test", "Specimen Transportation Charges",
    "Thalassemia Studies", "Thrombin Time", "Thrombophilia Gene Mutation", "Thrombophilia Panel(Hinduja Hospital)", "Thrombophilia Profile(Maxi) - GW",
    "Thrombophilia Profile(Mini)", "Thrombotic Profile.", "Urine Eosinophil Detection", "Vitamin K", "Vw-von Willebrand antigen", "WBC Total & Differential",
    "ACTH STAINING", "Acute Leukaemia Panel", "Acute Lymphoblastic Leukemia Panel", "ALK 1", "ALL PCR Panel", "AML COMBO (AML+FLP3)", "AML PCR Panel",
    "BARR BODY", "BCL2 By Fish", "Bcr-abl (Fish Method)", "BCR-ABL 1 Kinase Domain Mutation", "Bcr-abl -RT PCR", "BIOPSY EM (RANBAXY)",
    "Bone Marrow Aspiration (Reporting)", "Bone-Marrow Biopsy", "B-raff", "C4D By IHC", "CD19", "CD20", "CEBPA", "Chromogranin A (In Blood)",
    "Chromosomal Microarray", "Chronic Lymphoproliferative Disorder Panel", "c-KIT Mutation Analysis", "CLL BY FISH METHOD(2SET)", "C-MET",
    "CMV IHC SINGAL MARKER TISSUE", "Cmv Inclusion Antibodies", "C-MYC", "Comprehensive tumour panel (NGS panel)", "COPPER STUDY IN LIVER BIOPSY",
    "Cystic Fibrosis F 508", "Cytogenetics Bcr-abl T(9:22) Philadelphia Chromosome(c M L)", "Cytogenetics Del 13q (Multiple Myeloma)", "Cytology",
    "Cytospin", "Del(5q)", "DNA PLOIDY ANALYSIS BY FLOW CYTOMETRY", "Dr.Borges 2nd Opinion", "E cadherin IHC Marker", "E.R.", "EGFR Mutation study",
    "Elastic Stain", "Epilepsy panel", "FISH For EWSR1(t 11:22)", "Fish for Multiple Myeloma Panel translocation", "Flowcytometry Panel:acute Myeloid Leukemia (aml) Panel",
    "FLT3 By PCR", "FNAC (Interpretation)", "FNAC (Procedure)", "Frozen Section", "Frozen section (Outside)", "Genetic Mutation by N-ras",
    "Genetic Mutation For K-RAS", "Glioma_Panel", "HBB(Thalassemia Detection)", "HBE Mutation Detection", "Hemochromatosis Mutation(c282 y & H 63 D) HFE",
    "Her 2 By Fish Method", "Her2/neu(c-er-b2)", "Histopathology Second Opinion(Dr.Borges)", "HPV Duo ( DNA detector & PAP smear)", "IgH",
    "IHC for CMV", "IHC FOR IgG4", "Immuno Histochemistry", "Individual IHC marker", "JAK2 MUTATION PANEL Exons 12 -15",
    "Karyoting & FISH Trisomy((13,18,21,X,Y)", "KI 67", "Kidney Biopsy ( EM )", "Kidney Biopsy (IF)", "Kidney Biopsy (LM)", "Kidney Biopsy C4D by (IF)",
    "Kidney Biopsy(SV40)", "KIR-6.2", "Large IHC panel", "Large Specimen", "LIVER BIOPSY SECOND OPINION ( DR ANJALI AMRAPURKAR )",
    "Liver Biopsy(Report by Dr.Mukul Vijay)", "Lymphoma Tumour : Differential Diagnosis:immunohistochemistry (Z219)",
    "Lymphoma Tumour:Hodgkin's Disease:differential Diagnosis:immunohistochemistry (Z223)", "MDS PANEL", "Medium Specimen", "METS", "MPL1",
    "MSI by IHC", "MSI MARKER", "Mucicarmin Stain", "Muscle Biopsy (EM)", "NPM1", "P.R.", "Pap Smear", "Parental Karyotyping(5814b)", "PDL1",
    "Pearl Stain/ Iron Stain For Bone Marrow", "PP 65", "Radical Specimen", "Ring Chromosome Analysis", "ROS1", "SECOND OPINION (DR.ANJALI AMRAPURKAR)",
    "Second Opinion Charges (Blocks)", "Second Opinion Charges (Hinduja)", "Second Opinion Charges(Slides)", "Second Opinion(Dr.Anita Borges,slides + Blocks)",
    "SKIN Biopsy(IF)", "Skin Biopsy.", "SMA(EXON7&8 OF SMN1&2)", "Small Specimen", "Small Specimen Processed At Dr.Arun Chitale's Lab", "Special stains",
    "Tissue Processing By Microwave Technique", "Tzanck smear", "Urgent Histopathology(OPD)", "Urine For Decoy Cells", "1,25 Dihydroxy Vitamin D3, Serum",
    "14-3-3 Protein(CJD)", "17-Ketosteroid", "17-OH Progesterone", "1st Trimester Prenatal Screening (B-HCG & Pappa)", "25 Hydroxy Vitamin D",
    "Acetyl Choline Receptor Antibodies", "Acetyl Cholinesterrase Receptor Antibody", "ACTH", "Acute Encephalitis Panel", "Acute Hepatitis Virus Evaluation I",
    "Acute Hepatitis Virus Evaluation II", "Acute Hepatitis Virus Evaluation III", "ADH-Anti Diuretic Hormone (Vasopressin)", "Alfa Feto Proteins",
    "Allergen - Food Panel 7", "Allergen - Gluten", "Allergen - Individual", "Allergen Cat Dander (Immunocap method)", "Allergen -Eczema/GIT (Non-Veg &Veg) Panel",
    "Allergen Test (Bakers Yeast)", "Allergy Gluten", "Allergy (Egg White)", "ALLERGY (MILK PROTEIN)", "Allergy Screen", "Allergy Screen By Rast",
    "Allergy screening-Phadiatop", "Allergy Test ( Bermuda Grass )", "Allergy Test ( Cocco Powder )", "Allergy Test ( Coconut )",
    "Allergy Test ( Dermatophagoides F )", "Allergy Test ( Dermatophagoides P )", "Allergy Test ( House Dust Greer )", "Allergy Test ( Mustard )",
    "Allergy Test ( Peanut )", "Allergy Test ( Sunflower Seed )", "Allergy Test ( Timothy Grass )", "Allergy Test ( Wheat )", "Allergy Test (Bayleaf)",
    "Allergy Test (Milk)", "allergy Wheat", "Alpha -1- Antitrypsin", "Alpha DHT (Di- Hydrotestosterone)", "Amino Acid (Qualitative)",
    "Amino Levulinic Acid ( ALA)", "Aminoacidogram", "Amniocentesis Prenatal Panel", "Amniotic Fluid : Fish (18 X & Y)", "Amniotic Fluid Karyotyping",
    "Amniotic Fluid Torch", "Amniotic Fluid: Fish ( 13 18 21 X & Y)", "Amoebiasis Antibodies (IHA)", "ANA - Anti Nuclear Antibodies By IF", "ANA Blott",
    "ANCA BLOT", "Androstenedione (A4)", "Angelman Syndrom", "Anti Basal Ganglia Antibody (Hinduja)", "Anti Basal Ganglion Antibody",
    "Anti Cardiolipin IgG", "Anti Cardiolipin IgM", "Anti CCP", "Anti Ds DNA", "Anti GBM", "Anti Gliadin Antibodies IgA", "Anti Gliadin Antibodies IgG",
    "Anti HAV - IgG", "Anti HAV - IgM", "Anti HAV (Total) Antibodies To Hepatitis A Virus", "Anti HB core - IgM", "Anti HB core (Total)",
    "Anti HBe Antibodies", "Anti HBsAg Antibodies", "Anti HEV IgG", "Anti HEV IgM", "Anti Histones Antibody", "Anti JO-1", "Anti LKM Antibodies",
    "Anti Microsomal Antibodies", "Anti Mitochondrial Antibody (Qualitative)", "Anti Neuronal Antibody", "Anti Phospholipid Antibody IgG",
    "Anti Phospholipid Antibody IgM", "Anti Rabies Antibody", "Anti Ribosomal P IgG Antibodies", "Anti Saccharomyces Cerevisiae (ASCA) -IgG",
    "Anti Saccharomyces Cerevisiae (ASCA)-IgA", "Anti Smooth Muscle Antibodies (ASMA)", "Anti Sperm Antibody", "Anti TPO Antibodies",
    "Antibody Screen Package Class I & CLASS II", "Anti-HBC Total", "APCR(METROPOLIS)", "Arginine", "ASO - Anti Streptolysin O", "Aspergillus Antibodies",
    "Atypical Pneumonia Profile", "Autoimmune Liver Disease Profile - 2", "Autoimmune Liver Disease Profile-1", "B2 Transferrin Test",
    "Bacterial Antigen Detection CSF (5 Antigens)", "Beta .2.Glycoprotein I-IgG", "Beta 2 Glycoprotein I-IgM", "Beta 2 Microglobulin",
    "Beta-2 Microglobulin Urine", "Betadiglucan", "Bethesda Assay For Factor VIII Inhibitor", "B-HCG", "Biotinidase (Serum)",
    "Biotinidase-neonatal dried blood spot", "BK Polyoma Virus Detection.", "Blood Galactosemia", "BLOOD LYMPHO CULTURE", "Bordetella Pertussis IgG antibodies",
    "BRCA 1 &2", "Brucella IgG", "Brucella IgM", "Bullous Pemphigoid Antibody 230", "Bullous Pemphigoid Antidody 180", "C- Peptide", "C.E.A",
    "C1 Esterase Inhibitor", "C3", "C4", "Ca 125", "Ca 15.3", "Ca 19.9", "Ca 242", "Ca 72.4", "Cadnium", "Calcitonin", "CALR", "c-ANCA",
    "Carbamazepine/Tegretol", "CD25", "CD3", "CD3/CD4/CD8", "CD4", "CD4/CD8", "CD45", "CD8", "Celiac Profile (TTG IgA Abs Gliadin IgG& IgA Abs)",
    "Centromere Antibody", "Ceruloplasmin", "Chikungunya PCR", "Chlamydia Pneumoniae Antibodies", "Chlamydia Pneumoniae IgA Antibodies",
    "Chlamydia Pneumoniae IgG Antibodies", "Chlamydia Pneumoniae IgM Antibodies", "Chlamydia Trachomatis DNA", "Chlamydia Trachomatis IgA",
    "Chlamydia Trachomatis IgG", "Chlamydia Trachomatis IgM Antibodies", "Chromosomal(Karyotyping) Test", "Circulatory Immune Complex -IgM",
    "Citrulline(Quantitative)", "CMV DNA Detection (Qualitative Test)", "CMV DNA PCR (NEXUS LAB)", "CMV IgG", "CMV IgM", "CMV Inclusion Bodies",
    "CMV-DNA Viral Load (Quantitative Test)", "CMV-Quantitative Viral Load (Hinduja Hospital)", "Cold Agglutinins(Metropolis)", "Complement total (CH - 50)",
    "Complete Allergy Testing Panel", "Comprehensive Neonatal Screening Panel", "Copper( Serum)", "Cortisol (8:00 AM)", "Cortisol Free Urine (24 Hrs)",
    "Cortisol(4:00 PM)", "Cortisol(Random)", "Coxiella Burnetii IgM (Q fever) Serum", "Coxsackie Antibody -IgG", "Coxsackie Antobody -IgM", "CSF IgG",
    "CSF Immunoglobulin", "CSF Index Study", "CTG Repeat Myotonic Dystrophy", "Cyclosporin C0 (Nexus Lab)", "Cyclosporin C2 (Nexus Lab)", "Cyfra(Ca)21.1",
    "Cystatin C", "Cystic Fibrosis (IRT) Neonatal screen", "Cystic Fibrosis F508", "Cysticercus(Taenia Solium)-IgG CSF", "Cysticercus-IgG Antibodies",
    "CYTOGENETICS : PML Ra Ra t (15:17)", "Cytomegalovirus DNA Detector", "DELTA5 F508", "Dengue PCR", "Desmoglein Antibody I", "Desmoglein Antibody III",
    "DHEAS", "Di Hydro Testosterone", "Diazepam", "Digeorge Syndrom(22q11.2 deletion by Fish method", "Digoxin", "Dilantin", "DMD/BMD-79 EXONS",
    "DNA Kinship Analysis", "DNA Methylation Test", "Donor Specific Antibody", "Dopamin in Urine", "Double Marker", "Down Syndrom Screen-1st Trimester",
    "DPT Antibodies", "DSA( Donor Specific IgG Antibodies to Class 1 & 2", "Duchenne Muscular Dystrophy ( DMD) PCR test", "E Histolytica Antibody",
    "E.coli. O157 antigen", "E2 (estradiol)", "E3 (estriol)", "EBV (VCA) IgG", "EBV DNA PCR", "EBV DNA PCR(Quantitative)", "EBV Early Antigen IgG",
    "EBV(NA) IgG", "EBV(NA) IgM", "EBV(VCA) IgM", "Echinococcus ( Hydatid Serology) IgG- Serum", "Endomysial Antibody", "Endomysial Antibody IgA",
    "Enterocheck (Rapid Typhi IgG & IgM)", "Enterovirus RNA PCR", "Ethanol", "Everolimus", "EVEROLIMUS(NEXUS)", "EXENDED METABOLIC WORKUP",
    "Extractable Nuclear Antigen Profile", "Ferritin", "FGF 23", "Flow Crossmatch", "Folic Acid", "Food Allergen Testing", "Food Allergy - Banana",
    "Food Allergy - Milk", "Food Allergy - Onion", "Food Allergy - Tomato", "Free Beta HCG", "Free Light Chain (Free Kappa And Free Lambda)",
    "Free PSA", "Free PSA /PSA Ratio", "Free T3", "Free T4", "Free Testosterone", "FSH", "FTA Abs(IgM Antibodies to Treponema)",
    "FTA-Abs (IgG Antibodies To-Treponema)", "GAD-65 (Glutamic Acid Decarboxylase ) Antibody", "Galactose Quantitative",
    "Galactosemia Classical (Transferase)Quantitative", "Gamma Interferon", "Ganglioside IgG antibody panel", "Ganglioside IgM antibody panel",
    "Gastrin", "Glomerular Filteration Rate (GFR)", "Glutamate in Urine", "Glycine (BLOOD)", "Glycine(CSF)", "Growth Hormone", "Haemosiderin",
    "Ham's test", "Haptoglobin (Nephelomety)", "HAV RNA PCR", "HBeAg", "HBV DNA (Quantitative)-outsourced", "HBV DNA Detection (Qualitative)",
    "HBV DNA Genotyping Plasma", "HCV Antibodies Donor (bb)", "HCV genotyping", "HCV RNA Quantitative", "HCV RNA (Qualitative)", "HCV Viral load",
    "HCV-IgM Antibody", "HCV-IgM Antibody-outsourced", "HDV - Total Antibodies To Hepatitis Delta Virus", "HE4 with ROMA Index",
    "Heavy & Trace Metals Profile -1", "Heavy & Trace Metals Profile -2", "Helicobacter Pylori -IgA", "Helicobacter Pylori- IgG", "Helicobacter Pylori- IgM",
    "Hepatitis B Profile", "HEPATITIS B VIRUS DRUG RESISTANCE", "Hepatitis Delta Virus(HDV IgM)", "Hepatitis E Virus Detection by PCR method",
    "Hepatitis Profile - Complete", "Herpes Simplex I Antibody IgG", "Herpes Simplex I Antibody IgM", "Herpes Simplex II IgG", "Herpes Simplex II IgM",
    "HIRSUTISM PROFILE", "HIV 2 VIRAL LOAD", "HIV DNA Detector (Qualitative)", "HIV -Duo Antigen & Antibody Screen", "HIV EARLY DETECTION PROFILE FOR AGE > 2 YEARS",
    "HIV Genotyping And Drug Resistance Test Plasma", "HIV P-24 Antigen", "HIV-1 RNA Quantification (Viral Load)", "HIV-1-RNA Detection (Qualitative) Plasma",
    "HIV-2 RNA DETECTION QUALITATIVE", "HIV-2 Specific Western Blot Test", "HLA ABDR-Loci", "HLA B27 Studies By PCR Method",
    "HLA TYPING A,B,DR(HIGH RESOLUTION)", "HLA TYPING A,B,DR(LOW RESOLUTION)", "HLA TYPING A,B,DR,DQ (HIGH RESOLUTION)", "HLA Typing And Cross Matching ( Live )",
    "Holotranscobalamine (Active Vit B12)", "HS- CRP High Sensitivity", "HSV PCR I & II", "HSV PCR I & II ( RELIANCE)",
    "Hu Antibody(Paraneuroplastic Antibody)", "Human Papilloma Virus(HPV)", "IgA (Serum)", "IgD", "IgE (Serum)", "IgE by RAST Cotton Fibre and Dust",
    "IgE-Aspergillus", "IgG (Serum)", "IgG(CSF)", "IgG4 Subclasses", "IgM (Serum)", "IHA For Amoebiasis", "Immune Status Panel",
    "Immunofixation Qualitative (Urine)", "Immunofixation Qualitative(Serum)", "Immunofixation Quantitative (Serum)", "Immunofixation Quantitative (Urine)",
    "Immunoglobulin Total", "Infectious Mononucleosis (IgM)", "Influenza Virus A IgG", "Influenza Virus A IgM", "Inhibin A", "Inhibin B",
    "Insulin (Fasting)", "Insulin (Post Prandial)", "Insulin (Random)", "Insulin Antibody", "Insulin Like Growth Factor (BP-3)",
    "Insulin Like Growth Factor I (IGF-1)", "Interlukin-6", "Intrinsic Factor Antibody", "Islet Cells Antibodies", "Jak 2v617 F Mutation Detection",
    "Jak2 Exon 12 Mutation", "Japanese Encephalitis Virus", "KARYOTYPING", "Ketogenic Profile", "Lamotrigine level",
    "LC 1 (liver cytosolic lantigen type 1)", "Legionella Pneumonia IgG antibody serum", "Legionella pneumophila IgM antibody serum",
    "Leigh's Disease (LD)", "Leishmania antibody-IgG(for Kala Azar)", "LEPTIN", "Leptospira DNA PCR", "Leptospira IgG (Elisa)", "Leveteracetam",
    "LH", "Lyme IgG Antibodies", "Lyme IgM Antibodies", "Lymphocyte Enumeration", "MAG Antibodies", "Measles (Rubeola) IgG", "Measles(Rubeola) IgM",
    "MECP2 MUTATION", "Meningo Encephalitis Panel", "Metabolic Disorder Study (Blood+Urine)", "Milk & Milk Product Package {Allergy}",
    "MPO(p-ANCA) By ELISA", "MS Neogen (Metabolic Disorder)", "Mullerian Inhibiting Substance (AMH)", "Mumps -IgM Antibodies", "Mumps-IgG Antibodies",
    "Musk Antibody Serum", "MYCOPHENOLATE (NEXUS)", "Mycoplasma Penumoniae IgG Antibody", "Mycoplasma Penumoniae IgM Antibody",
    "Neisseria Gonorrhoeae DNA PCR", "Neonatal Screening for Galactosemia", "Neurocystic Sarcosis Panel", "Neuromyelitis Optica Antibodies (NMO)",
    "Neuronal Antibody Profile", "Nicotine Metabolite", "Niemann Pick A/B (LZ-11)", "Nitroprusside Test Urine", "NKH(Non Ketotic Hyperglycemia)",
    "NMDA receptor antibody", "Nor-Adrenaline (Nor-Epinephrine)-Plasma", "Nor-Epinephrine in Urine", "NSE(Neurone Specific Enolase)", "Oligoclonal Band",
    "OXCARBAZIPINE", "P1NP (Total) Oestoporosis Monitoring", "Pan Neurotropic Virus Panel.", "p-ANCA", "Panel Antibody Screening",
    "PAN-FUNGAL DNA BY PCR", "Pappa-Pregnancy Associated Plasma Protein", "PARACETEMOL(ACETAMINOPHEN)", "Paraechovirus PCR", "Parietal Cell Antibody",
    "Parvovirus B19- DNA PCR", "Parvovirus IgG", "Parvovirus IgM", "PCR FOR FRAGILE X- CHROMOSOME", "PDGFR ALPHA (HES)", "PDGFR BETA (CMML)",
    "Penicllin Group Allergy Panel", "Phenobarbitone", "Phospholipase A2 receptor Antibody", "PIVKA II", "Plasma Adrenaline (Epinephrine)",
    "Plasma Renin Activity (PRA)", "Platelet Antibodies", "PML Ra Ra (15 : 17)", "PMP22 GENE", "P-NBS 22 Disorder", "Pooled F.S.H", "Pooled Prolactin",
    "PR3 by EIA (c- ANCA)", "Prader-Willi/Angelman Syndrome (Microdele 15q9-13)FISH Method", "Procalcitonin(Quantitative)", "Progesterone", "Prolactin",
    "Proteolipid Protein 1 Mutation Test", "PSA", "PTH (Intact PTH)", "PTH related Peptide", "Quadruple Marker Test", "Qualitative Detection of EBV Markers",
    "RBC FOLATE BLOOD", "RealTime PCR Swine Flu", "Respiratory Tract Infection Profile IgG", "Respiratory Tract Infection profile IgM",
    "RET-PROTO-ONCOGEN(MEN)", "RIBH Molecular Identification", "Ricketssia PCR", "RNP-SM Antibody", "Ro (SSA-Soluble Subtance A) Antibody",
    "RSV- Respirtory Syncytial Virus IgM", "RSV(Respiratory Syncytial Virus) IgG", "Rubella IgG", "Rubella IgM", "Scl -70", "Scrub Typhus Antibody",
    "Serotonin", "Serotonin in Urine", "Serum Aldosterone", "Serum Erythropoietin", "Serum Immunofixation Electrophoresis",
    "Serum Protein Electrophoresis (SPE)", "SHBG (sex Hormone Binding Globulin)", "Single antigen Bead (SAB) Class 2", "Single Antigen Bead(SAB) Class- 1",
    "Sirolimus", "Sirolimus (Nexus Lab)", "SLA-soluble liver antigen", "SM ( Smith ) Antibody", "SMN2 COPIES WITH TRANSPORTATION CHARGE",
    "SOLUBLE LIVER ANTIGEN", "SPINK,PRSS-1", "SRY DELETION BY FISH", "Ssa Ro Antibody", "Ssb-la Antibody", "Stem Cell Marker", "Stool for H.Pylori",
    "Succinyl Acetone", "t (11;14) ;by FISH", "t (15 :17) translocation", "t(9;22) by FISH", "T.Solium IgG", "T3", "T3T4TSH", "T4", "Tacrolimus",
    "Tacrolimus (Metropolis lab)", "Tacrolimus AID", "Tacrolimus Genotyping", "Tacrolimus Genotyping (R)", "TACROLIMUS(HINDUJA)",
    "Taenia Solium IgG (Cysticercus)", "Tandem MS", "TB Genotyping With Drug Sensitivity", "TB Genotyping With Extened Drug Senstivity", "TB PCR",
    "TB Platinum -GW", "TB-Gold-GW", "TB-IgA", "Theophyline", "Thiamine (Vitamin B1)", "Thyroglobulin", "Thyroglobulin Antibody (ATA)",
    "Thyroid Antibodies - ATAB", "Tissue Transglutaminase IgA", "TMS", "TMS With Biotinidase (Neogen Lab)", "Torch - 10 (with Chlamydia)",
    "Torch - 4 IgG (Toxo/CMV/Rubella/HSV)", "Torch - 4 IgM", "Torch - 8 IgG/IgM", "Total Testosterone", "Toxoplasma Antibodies IgG",
    "Toxoplasma Antibodies IgM", "Toxoplasma IgG (CSF)", "Toxoplasma-DNA Detection", "TPMT Activity", "TPMT GENOTYPING", "Transferrin",
    "Triple Marker", "TSH", "TSH (H & N)", "TSH Receptor Antibody", "U1Sn-RNP(68 KDa)", "Urine Beta HCG", "Urine Organic Acid",
    "Urine package for Phenylketone", "Urine Protein Electrophoresis", "Valporic Acid (Valparin)", "Varicella (Herpes) Zoster -IgM Antibodies",
    "Varicella (Herpes) Zoster-IgG Antibodies", "Varicella Zoster PCR", "VGKC- Voltage gated potassium channel serum", "Vitamin A (Retinol)",
    "VITAMIN B1(THIAMINE)", "Vitamin B12", "Vitamin B6 (Pyridoxine)", "Vitamin C", "Vitamin- E (Tocopherol)", "VMA", "Voriconazole",
    "Western Blot Test For HIV 1-2 Antibodies", "Whole Neurology Panel", "William's Syndrome", "YO Antibody(Paraneuroplastic Antibody)", "Zinc",
    "5 Antigen Panel (Hinduja)", "Acid Fast Bacilli Drugs Susceptibility MGIT (10 drugs panel)", "Acid fast bacilli susceptibility for 1 drug (automated)",
    "Acid Fast Bacilli Susceptibility For 13 Drugs (automated)", "Acid Fast Bacilli Susceptibility For 5 Drugs(automated)", "Acid Fast Stain And Rapid Culture",
    "Acid Fast Susceptibility (1st Line Sire)", "Aerobic Culture (BacT/Alert) And Sensitivity", "Aerobic/Anaerobic Blood culture",
    "AFB Culture By Conventional LJ Medium", "AFB Identification And speciation of MTB And MOTT by Hains Pure culture",
    "AFB Rapid Culture For Urine(Three Samples)", "AFB Stain (Fluorescent Microscopy)", "Air surveillance study -Aerial load", "Albert Stain",
    "Anaerobic Culture", "Anaerobic Culture By BacT/Alert", "Antimicrobial Susceptibility", "Atypical Mycobacterial Susceptibility (MIC)",
    "Autoimmune Encephalitis Panel", "Aztreonam Ezy MIC strip", "BacT/Alert Fungal Culture", "BacT/Alert Tb Culture For Blood And Bone Marrow",
    "Bacteriological Examination of Air", "Biofire - Lower Respiratory Tract Panel", "Biofire Gastro- Intestinal panel- Stool sample",
    "Biofire Meningitis panel- CSF sample", "Biofire Upper respiratory tract- Throat swab", "Blood Culture identification by MALDI- TOFF",
    "Bronchial Lavage Culture And Sensitivity", "Brucella by tube agglutination", "Brucella culture", "Calcofluor Stain",
    "Ceftazidime -Avibactum + Aztreonam Ezy MIC strip", "Ceftazidime-Avibactum", "Central Line Tip", "Colistin broth micro dilution (BMD)",
    "Collection Charges (COVID-19)", "Conjunctival Swab Culture", "COVID-19", "Cryptococcus Antigen", "CSF Culture And Sensitivity",
    "Culture Identification", "Culture Miscelleneous", "Culture susceptibility testing", "cultured AFB other than tuberculosis (MOTT) DST For rapid growers",
    "DHEA", "Drug Sensitivity For AFB Each Drug Price Ext.", "E.T. Secretion Culture", "E.T. Suction Tip Culture", "EBV nuclear antigen (EBNA)",
    "Environmental Surveillance study -Surface swab", "ETO Biological indicator Sterilization Surveillance", "Fanconi anemia chromosomal breakage study",
    "FilmArray blood culture identification(BIOFIRE)", "Fluid Culture And Sensitivity", "Fosfomycin Ezy MIC strip", "Fungal Culture",
    "Fungal Stain (KOH Mount)", "Fungal Susceptibility (Automated:Vitek 2)", "Fungal Susceptibility with MIC", "Genexpert Clostridium difficile toxin",
    "Gram Stain", "Hain's Test for 1st Line Drugs", "Hain's Test for 2nd Line Drugs", "Hanging Drop For Vibrio", "Hanta Virus IGM",
    "Helicobacter Pylori -Culture", "India Ink Preparation", "Inherited marrow failure syndrome panel", "Isoniazid", "JC VIRUS - DNA",
    "Legionella Ag For Urine", "Leptospira Detection", "Liver Abscess Examination For Amoebiasis", "LTSF Biological indicator Sterilization Surveillance",
    "M.T. Skin Test", "MIC For Nocardia Species", "MIC For Rapid Growing Mycobacteria", "Microbiological Food Analysis", "Microsporidium From Stool",
    "Modified ZN stain", "MPN mutation Panel", "MRSA Screening Package", "Multiple Sclerosis profile", "Nasal Swab For M.R.S.A.",
    "Nocardia culture and sensitivity", "Occult Blood(Sputum)", "PARANEOPLASTIC DISORDER (Outsourced )", "Pneumococcal Antigen (Urine)",
    "Pneumocystis carnii PCR (PCP)", "Pus Culture", "Pyrosequencing XDR TB", "Rifampicin", "Smear AFB - Acid Fast Stain (AFB)",
    "Special Staining For Cryptosporidium/Microporidium/Isospora", "Sputum Culture", "Steam Biological indicator Sterilization Surveillance",
    "STERILITY CHECK OF BLOOD BAG", "STERRAD CYCLE SURE 24 -(Sterilisation Surveillance)", "Stool Culture", "Streptococcus Group B Antigen -urine",
    "Swine Flu Kit", "TB Package", "TB Panel", "TB Panel (Cytology)", "TB Panel(Biopsy)", "TB single drug sensitivity by MGIT",
    "Tb Species Identification", "Tb Susceptibility-Kepo(Hinduja)", "Tb Susceptibility-PZA (Hinduja)", "Tb Susceptibility-SIRE(Hinduja)",
    "TB-Susceptibility for MACC", "Throat Swab Culture", "Urine Culture", "Vaginal Smear Examination", "Viral Transport Swab", "Water Testing",
    "Wet Mount - Microscopy", "Wound Swab Culture", "Xpert Carba-R", "XPert MTB/RIF", "Yersinia Enterocolitica antigen", "Yersinia Enterocolitica culture",
    "Aquaporine IgG", "Aspergillus Galactomannan", "Chickungunia IGM Serum", "Dengue Antigen (Quantitative by ELISA)", "Dengue IgG -Elisa",
    "Dengue IgM-Elisa", "Dengue Immunochromatographic Test", "HbsAg By Chemiluminescence", "HbsAg By Elisa", "HbsAg By Spot", "HCV By Chemiluminescence",
    "HCV By Elisa", "HCV By Spot", "HIV 1/2 By Elisa", "HIV 1/2 By Spot", "HTLV-1/2 SEROLOGY", "L.E.test", "Leptospira IgM", "Monospot Test (Paul Bunnel)",
    "Pre Procedure Viral Marker", "RA Test", "RF By Nephelometry Method", "Scrub typhus IgM antibodies", "TPHA FOR SYPHILIS", "V.D.R.L.(RPR)",
    "Viral Markers.", "Weil Felix Test", "Widal Test"
  ];

  const radiologyServices = [
    "CT 3D Scan ( Single Joint )", "CT Abdomen And Pelvis Contrast", "CT Abdomen Contrast", "CT Abdomen Pelvis Plain", "CT Abdomen Plain",
    "CT Angiography", "CT Brain Direct Contrast", "CT Brain Plain", "CT Brain Plain Plus Contrast", "CT Brain with Cervical Spine Screening",
    "CT Cervical Spine Contrast", "CT Cervical Spine Plain", "CT Chest & Abdomen Contrast", "CT Chest Abdomen & Pelvis Contrast",
    "CT Chest Abdomen & Pelvis Plain", "CT Chest Contrast", "CT Chest Plain", "CT Cisternography", "CT Coronary Angiography", "CT Dacrocystogram",
    "CT Emergency Charges", "CT Evaluvation For Obesity", "CT Extremity Plain", "CT Extremity With Contrast", "CT Face", "CT Fistulogram / Sinogram",
    "CT FNAC", "Ct Guided Biopsy Complex", "Ct Guided Biopsy Simple", "CT GUIDED DRILLING OF OSTEOID OSTEOMA", "CT Guided Procedure",
    "CT GUIDED RADIO FREQUENCY ABLATION PROCEDURE", "CT HRCT Chest Plain", "CT HRCT Of Temporal Bone", "CT IVP", "CT KUB Plain",
    "CT Limited Study (Contrast)", "CT Limited Study (Plain)", "CT Myelogram", "CT Neck (Thyroid) Contrast", "CT Neck (Thyroid) Plain",
    "CT Orbit Plain", "CT Orbit With Contrast", "CT Para Nasal Sinus (limited)", "CT Pelvis Contrast", "CT Pelvis Plain", "CT RT Plain IV Contrast",
    "CT RT Plain IV Plus Oral Contrast", "CT single Joint", "CT Spine", "CT Urography", "CT Wrist Joint", "HRCT for COVID testing",
    "CT CHARGES PLUS ANAESTH. STANDBY", "Kidney Biopsy Needle Usg Guided Proc .by Nephrologist", "Pelvimetry", "Pigtell Abssess Drain CT Guided",
    "2D echo ( bubble)", "2D Echo (Emergency)", "2d Echo Portable", "2D Echo portable with contrast", "2d Echo Screening", "2D Echo Screening (Portable)",
    "2D Echo with contrast", "2D-Echo", "3D Echo", "Adenosen Stress Echo", "Ambulatory Bp Monitoring", "Cardiac Monitoring Charge",
    "Cardio-Pulmonary Exercise Testing", "Cardio-Pulmonary Exercise Testing With Contrast Stress Echo", "Cardio-Pulmonary Exercise Testing With Stress Echo",
    "Dobutamin Stree Echo With Contrast", "Dobutamin Stress Echo", "Fetal Echo", "Holter Monitor", "Holter Monitor 48 Hrs", "Intra - Cath TEE",
    "INTRA OP- ESOPHAGEAL ECHO(TEE)", "Paed. 2d-Echo (SNCU)", "Paediatric 2d Echo", "Paediatric Echocardiography", "Stress Echo",
    "Stress Echo With Contrast", "Stress Test", "Stress Test/2D Echo", "TEE (Portable)", "Trans-esophageal Echo ( Tee )", "Contrast Charges",
    "Contrast Charges - Pediatric", "Extended M.R.I.", "Health check up M.R.I. One part", "M.R.I & M.R.A Brain", "M.R.I Emergency Charges",
    "M.R.I Fetal", "M.R.I Fistulogram", "M.R.I Limited Screening", "M.R.I Limited Study", "M.R.I liver Fat Quantification", "M.R.I Radiation Plan",
    "M.R.I SI JOINT", "M.R.I WHOLE BODY DEDICATED", "M.R.I WHOLE BODY SCREENING", "M.R.I. Abdomen With Pelvis", "M.R.I. Angio Head & Neck",
    "M.R.I. Ankle", "M.R.I. Arm", "M.R.I. Brachial Plexus", "M.R.I. Brain", "M.R.I. Brain & Angio With Spine Screening",
    "M.R.I. Brain & Angiogram With Cervical Spine", "M.R.I. Brain Plus Neck", "M.R.I. Brain Plus Orbit Plus Optic Cuts",
    "M.R.I. Brain With Whole Spine Screeing", "M.R.I. Brain With Cervical / LS Spine", "M.R.I. Brain With Contrast & Angio & Venogram",
    "M.R.I. Brain With Contrast& Angiogram", "M.R.I. Brain With One Part Screening", "M.R.I. Brain With One Part Study",
    "M.R.I. Brain With Spectroscopy", "M.R.I. Brain With Two Part Study", "M.R.I. Brain With Venogram", "M.R.I. Brain With Venogram With Contrast",
    "M.R.I. Breast", "M.R.I. Cardiac", "M.R.I. Chest", "M.R.I. Chest & Neck", "M.R.I. Contrast Charges -Adult (Regular)",
    "M.R.I. Contrast Charges -Special Study.", "M.R.I. Contrast Study", "M.R.I. Dorsal Spine & Cervical Spine With Shoulder Screening",
    "M.R.I. Elbow Joint (Single)", "M.R.I. Hip & Thigh", "M.R.I. Hip Joint (Single)", "M.R.I. Hip With Screening Of Lower Spine",
    "M.R.I. IAM (Vertigo Package)", "M.R.I. Knee Joint ( Both)", "M.R.I. Knee Joint ( Single)", "M.R.I. Lower Limb Angio",
    "M.R.I. Lumbar Spine with SI Joint", "M.R.I. Neck", "M.R.I. Orbit", "M.R.I. Pelvis", "M.R.I. Pelvis With Hips", "M.R.I. Plain",
    "M.R.I. Post Procedure Limited Study", "M.R.I. Prostate", "M.R.I. Renal Angiography", "M.R.I. Shoulder", "M.R.I. Shoulder Arthrography",
    "M.R.I. Shoulder With One Part Screening", "M.R.I. Shoulder With One Part Study", "M.R.I. Spine Cervical",
    "M.R.I. Spine Cervical With Screening of Dorsal Spine", "M.R.I. Spine Cervical With Screening of Lumbar Spine",
    "M.R.I. Spine Cervical With Whole Spine Screening", "M.R.I. Spine Dorsal", "M.R.I. Spine Dorsal & Cervical",
    "M.R.I. Spine Dorsal With Screening of Cervical Spine", "M.R.I. Spine Dorsal With Screening of Lumbar Spine",
    "M.R.I. Spine Dorsal With Whole Spine Screening", "M.R.I. Spine Lumbar", "M.R.I. Spine Lumbar & Cervical", "M.R.I. Spine Lumbar & Dorsal",
    "M.R.I. Spine Lumbar With Screening of Cervical Spine", "M.R.I. Spine Lumbar With Screening of Dorsal Spine",
    "M.R.I. Spine Lumbar With Whole Spine Screening", "M.R.I. Thigh / Foot", "M.R.I. Upper Abdomen", "M.R.I. Upper Limb Angio", "M.R.I. Venogram",
    "M.R.I. Whole Spine Screening", "M.R.I. Wrist Joint (Single)", "M.R.I.Brain & Orbit", "MR Angio Brain With Venogram", "Stroke Protoco",
    "Mammography", "Mammography (Bilateral)", "Mammography (Unilateral)", "Mammography with Tomosynthesis", "Mammography/ Sono Mammography",
    "Specimen Mammography", "Unilateral Mammography with Tomosynthesis", "C.d.charges", "Dopple Studies - AV Fistula", "Doppler Screening",
    "Doppler Studies - Carotid", "Doppler Studies - Carotid and Radial", "Doppler Studies - Lower Extremities Arterial (Bilateral)",
    "Doppler Studies - Lower Extremities Arterial Single Limb", "Doppler Studies - Lower Extremities Venous (Bilateral)",
    "Doppler Studies - Lower Extremities Venous Single Limb", "Doppler Studies - Mesentric", "Doppler Studies - Obstetric", "Doppler Studies - Pelvis",
    "Doppler Studies - Penile", "Doppler Studies Portal Vein", "Doppler Studies - Renal", "Doppler Studies - Scrotum", "Doppler Studies - Transcranial",
    "Doppler Studies - Upper Extremities Arterial Single Limb)", "Doppler Studies - Upper Extremities Venous (Single Limb)",
    "Doppler Studies- Upper Extremities Arterial (Bilateral)", "Doppler Studies- Upper Extremities Venous (Bilateral)",
    "Evlt Procedure- Unilateral (endovenous Laser Treatment For Vericose Vein)", "Evlt Procedure-bilateral (endovenous Laser Treatment For Vericose Vein)",
    "Fluid Drain (USG) Diagnostic", "Fluid Drain (USG) Therapeutic", "Growth scan less than 10 day interval", "Obs growth Scan",
    "Picc Line ( Bed Side -Icu) USG", "Pigtell Abssess Drain USG Guided", "Single Limb (Portable)", "Sono Mammography", "Twin Anomaly Scan",
    "Twin Echo", "Twin NT Scan", "Usg Guided Procedure-(medium)", "Usg Guided Procedure-(small)", "Usg 3d Pelvis", "Usg Abdomen & Pelvis",
    "Usg Abdomen & Pelvis(portable)", "Usg Abdomen (portable)", "Usg Anomaly Scan", "Usg B Scan", "Usg Biphysical Profile",
    "Usg Breast Mass Localization", "Usg Chest", "Usg Chest(portable)", "Usg- Cranial (portable)", "USG Cranium", "Usg Fat Evaluation",
    "Usg Follicular Monitoring Package", "Usg Guided Procedure- Major", "Usg Guided Biopsy", "Usg Guided Breast Biopsy",
    "USG Guided diagnostic tapping", "USG GUIDED EVLT PROC -RADIOLOGIST FEES", "Usg Guided Procedure - Minor", "USG guided theraputic tapping",
    "Usg Intra Operative", "Usg Kub", "Usg Kub Portable", "Usg Musculoskeletal", "Usg Neck", "Usg Pelvis", "Usg Portable Charges (machine)",
    "USG Pregnancy / Earlier Pregnancy", "USG Pregnancy 3D/4D / Anomaly Scan.", "Usg Pregnancy Fetal Echo", "USG Pregnancy Nuchal Scan",
    "Usg Screening (small Part)", "Usg Scrotum", "Usg Thyroid", "Usg Turs Prostate", "Usg Upper Abdomen", "Usg-mcu Pedeatric", "Viability scan",
    "Bilbao Dotter Tube", "DTPA scan (outsource)", "Fluroscopy", "FLUROSCOPY FOR SCREENING", "Hysterosalpingogram ( HSG )",
    "Intracostal Drainage Tube Removal", "Material Charges", "PFR with reversibility", "Plurodesis",
    "Radiology- Ba-enema For Hydrostatic Reduction Of Intussusception", "X- ray Both Heels Lat/ Axial", "X- Ray Charge", "X- ray Mandible P.A.",
    "X-ray Abd (portable)", "X-ray Abd. A.P.", "X-ray Ankle AP/ LAT", "X-ray Ankle AP/LAT(Portable)", "X-ray Barium Enema",
    "X-ray Barium Meal Follow Through", "X-ray Barium Stomach & Duodenum", "X-ray Barium Swallow", "X-ray Both Ankle AP/ LAT",
    "X-ray Both Ankle AP/LAT (Portable)", "X-ray Both Elbow AP/ LAT", "X-ray Both Elbow AP/LAT (Portable)", "X-ray Both Femur AP /LAT View",
    "X-ray Both Femur AP/LAT (Portable)", "X-ray Both Foot AP (Portable)", "X-ray Both Foot AP / LAT", "X-ray Both Foot AP / LAT (Portable)",
    "X-ray Both Foot AP/ Oblique View", "X-ray Both Foot Oblique", "X-ray Both Forearm AP/LAT View", "X-ray Both Hand AP/ Lat (Portable)",
    "X-ray Both Hand AP/ Lat View", "X-ray Both Hands P.A.", "X-ray Both Heels", "X-ray Both Heels Lateral", "X-ray Both Humerus AP / Lat View",
    "X-ray Both Knee AP", "X-ray Both Knee AP (Portable)", "X-ray Both Knee AP / Lat View", "X-ray Both Knee AP/Lat (Portable)",
    "X-ray Both Knee Lat", "X-ray Both Knee Skyline", "X-ray Both Mastoids Schullers View", "X-ray Both Orbit AP / Lat", "X-ray Both Shoulder AP View",
    "X-ray Both T.M. Joints", "X-ray Both Wrist AP/ Lat View", "X-ray Cervical Spine AP / Lat View", "X-ray Cervical Spine AP/Lat (Portable)",
    "X-ray Cervical Spine Both Oblique", "X-ray Cervical Spine Ext/Flex", "X-ray Cervical Spine Open Mouth", "X-ray Cervico-dorsal Spine AP/Lat",
    "X-ray Cervico-dorsal Spine AP/Lat (Portable)", "X-ray Chest (Portable)", "X-ray Chest Lat", "X-ray Chest Oblique", "X-ray Chest P.A.",
    "X-ray Chest/LS Spine", "X-ray Clavicle AP", "X-ray Coccyx Spine AP", "X-ray Coccyx Spine Lat", "X-ray Conraygram", "X-ray Dacrocystography",
    "X-ray Dorsal Spine AP/Lat (Portable)", "X-ray Dorsal Spine AP/Lat View", "X-ray Dorso-lumbar (Portable)", "X-ray Dorso-lumbar Spine AP/Lat",
    "X-ray Elbow AP/ Lat", "X-ray Elbow AP/Lat (Portable)", "X-ray Femur AP", "X-ray Femur AP (Portable)", "X-ray Femur AP/ Lat View",
    "X-ray Femur AP/Lat (Portable)", "X-ray Femur Lat", "X-ray film (extra)", "X-ray Finger AP/Lat", "X-ray Fingre AP/Lat (Portable)",
    "X-ray Foot AP/Lat", "X-ray Foot AP/Oblique", "X-ray Foot AP/Oblique (Portable)", "X-ray Fore Arm AP/Lat", "X-ray Forearm AP/Lat (Portable)",
    "X-ray Hand AP/Oblique", "X-ray Hand with Wrist AP", "X-ray Hip (Portable)", "X-ray Hip AP & Lat (Portable)", "X-ray Hip AP/Lat View",
    "X-ray Hip Joint AP", "X-ray Hip Joint Lateral", "X-ray Humerus AP", "X-ray Humerus AP (Portable)", "X-ray Humerus AP / Lat",
    "X-ray Humerus AP/Lat (Portable)", "X-ray Humerus Lat", "X-ray Intra Venous Urography (IVU)", "X-ray IVP", "X-ray Knee AP (Portable)",
    "X-ray Knee AP/ Lat", "X-ray Knee AP/Lat (Portable)", "X-ray Knee AP/Lat/Skyline", "X-ray KUB", "X-ray L.S. Spine AP/Lat (Portable)",
    "X-ray Leg AP/Lat", "X-ray Lumber Spine Both Oblique", "X-ray Lumber Spine Ext/Flex", "X-ray Lumbo Sacral Spine AP/Lat",
    "X-ray Mandible PA (Portable)", "X-ray Mandible/ Views", "X-ray Mastoids", "X-ray MCU", "X-ray Nasal Bone", "X-ray Nasopharynx", "X-ray OPG",
    "X-ray Orbits", "X-ray P.B.H.", "X-ray Para Nasal Sinuses", "X-ray PBH (Portable)", "X-ray Pbh AP/Lat", "X-ray Pelvimetry",
    "X-ray Pelvis With Both Hips", "X-ray Pns Caldwel's", "X-ray Pns Waters", "X-ray Portable (Single)", "X-ray Sacrum Coccyx Spine AP/Lat",
    "X-ray Scanogram", "X-Ray Scanogram (PAED)", "X-ray Scaphoid Views", "X-ray Shoulder Abd / Ad", "X-ray Shoulder AP",
    "X-ray Shoulder AP/Lat (Portable)", "X-ray Shoulder Axiallary", "X-ray Shoulder- Lateral", "X-ray Sialogram", "X-ray Single View",
    "X-ray Sinogram", "X-ray Skull AP/Lat", "X-ray Skull AP/Lat (Portable)", "X-ray Skull Lateral", "X-ray Small Bowel Enema", "X-ray Sternum",
    "X-ray Tibia/ Fibula AP/Lat", "X-ray Tibia/Fibula (Portable)", "X-ray Urethrogram", "X-ray Wrist AP/Lat", "X-ray Wrist AP/Lat (Portable)",
    "X-ray Wrist AP/Oblique", "X Ray IOPA (Paediatric)"
  ];

  const rehabServices = [
    "Physiotherapy - 1 Modality Treatment", "Physiotherapy - 2 Modality Treatment", "Physiotherapy - 3 Modality Treatment",
    "Physiotherapy - 4 Modality Treatment", "Physiotherapy Lymphapress", "Physiotherapy Lymphapress Short", "Physiotherapy Lymphodema Treatment",
    "Physiotherapy- shoulder Rehabilitation (12 Sections)", "Physiotherapy Treatment- Long", "Physiotherapy Treatment- Medium",
    "Physiotherapy Treatment -Session", "Physiotherapy Treatment Session Long", "Physiotherapy Treatment Session Special",
    "Physiotherapy Treatment -Short", "Physiotherapy Treatment-Minor", "Physiotherapy-Cardiac Rehabilitation", "Physiotherapy-Taping Long",
    "Physiotherapy-Taping Short", "Physio-Treatment Modality 1 Package(5 days)", "Physio-Treatment Short Package (5 days)"
  ];

  const gastroenterologyServices = [
    "Colonoscopy Polypectomy", "Endoscopic CRE Balloon Dialatation", "Delcom Expandable Biliary Stent 8cm", "Gastroscopy With Glue Injection",
    "Gastroscopy", "Savary-gillard Dilation Of Esofegus", "Flex. Sigmoidoscopy", "Achalasia Cardia Dilatation", "ERCP Uncomplicated (Plastic Stent)",
    "ERCP Complicated (Single Stenting.Mechanical Lithotripsy)", "ERCP Stent Removal", "Endoscopy Band Ligation", "Endoscopy Foreign Body Removal",
    "Colonoscopy", "Endoscopic Argonplasma Coagulatic With Hemoclip Insersion", "Gastroscopy With Polypectomy", "Gastroscopy with Injection Treatment of Ulcer",
    "Anaesthetist Charges (L.A.)", "Anaesthetist Charges (G.A.)", "Meterial Consumables", "Intra-op OGD Scopy", "Endoscopic Gastrostomy", "ERCP",
    "PTBD (Percutaneous Transhepatic Billeary Drinage)", "Endoscopic PEG Removal", "Insersion Of Oesophagal Applicator For Brachitherapy",
    "Endoscopic Gastrotomy (Indian PEG)", "Capsule Endoscopy (Incl. Capsule Charge)", "Endoscopy-N.J. Tube Insertion", "Endoscopic PEG Replacement",
    "Esophageal/Ano-rectal Manometry", "Scelerotherapy", "Metal Stenting (Endotracheal/Esophageal/Endoscopic/Colonic)", "ERCP - Supramajor (Multiple Stents)",
    "Cauterization (Gave Radiation Proctitis)", "Biliary Rendezvous", "PH Metry", "Gastroscopy & Botox", "Capsule Endoscopy",
    "ESOPHAGEAL VARICEAL STENTING", "Endoscopic Ulcer Bleed Treatment", "Bronchoscopic Foreinbody Removal", "Bronchoscopy with TBNA",
    "Bronchoscopy with Therapatic Lavage", "BRONCHOSCOPY WITH ASPIRATION BIOPSY", "ENDOSCOPY VARICEAL SCLEROTHERAPY", "ENDOSCOPIC BALLOON REMOVAL",
    "ENDOSCOPIC BALLOON INSERSION", "Gastroscopy with Biopsy", "Colonoscopy with Biopsy", "Endoscopy - Ryles Tube Insertion",
    "Colonoscopy - Decompression", "SIGMOIDOSCOPY WITH BIOPSY OR BRUSHING", "OGD WITH BIOPSY OR BRUSHING", "COLON DIAGNOSTIC WITH BIOPSY/BRUSHING",
    "COLON POLYTECTOMY", "COLON STENT", "COLON WITH LASER", "SIGMOIDOSCOPY AND BALLOON DILATATION", "SIGMOIDOSCOPY AND BANDING",
    "SIGMOIDOSCOPY AND POLYPECTOMY", "SIGMOIDOSCOPY AND STENTING", "SIGMOIDOSCOPY DIAGNOSTIC", "SIGMOIDOSCOPY WITH INJECTION",
    "SIGMOIDOSCOPY WITH LASER", "OGD SCLEROTHERAPY", "ERCP AND METAL STENTING", "Gastroscopic Argonplasma Coagulation",
    "Gartroscopic Hemoclip Insersion", "COLONSCOPIC APC RADIATION PROCTITIS", "GASTROSCOPIC APC FOR GAVE", "Endloop Handle & Applicator Charges",
    "SINGLE BALLOON ENTEROSCOPY(RETROGRADE)+NBI+APC (OUTSOURCE)", "ANAESTHETIST CHARGES - TRACHEL STENTING", "COMPLICATED COLONIC POLYPECTOMY",
    "Fibroscan", "Duodenoscopy", "Colonoscopy with Haemoclip", "Gastroscopy with Haemospray", "Colonoscopy with Haemospray",
    "Endoscopic Intubation", "Gastroscopy with Haemoclip."
  ];

  try {
    for (const deptData of newDepartments) {
      const existing = await db.select().from(hospitalServiceDepartments).where(eq(hospitalServiceDepartments.slug, deptData.slug));
      if (existing.length === 0) {
        const [dept] = await db.insert(hospitalServiceDepartments).values(deptData).returning();
        console.log(`Created department: ${dept.name}`);
        
        let servicesToAdd: string[] = [];
        if (deptData.slug === "uro-surgery") servicesToAdd = uroSurgeryServices;
        else if (deptData.slug === "pathology") servicesToAdd = pathologyServices;
        else if (deptData.slug === "radiology") servicesToAdd = radiologyServices;
        else if (deptData.slug === "rehab-services") servicesToAdd = rehabServices;
        else if (deptData.slug === "gastroenterology") servicesToAdd = gastroenterologyServices;
        
        if (servicesToAdd.length > 0) {
          const servicesToInsert = servicesToAdd.map(name => ({ departmentId: dept.id, name }));
          await db.insert(hospitalServices).values(servicesToInsert);
          console.log(`Added ${servicesToAdd.length} services to ${dept.name}`);
        }
      } else {
        console.log(`Department ${deptData.name} already exists, skipping...`);
      }
    }

    console.log("Batch 4 services seeding completed successfully!");
  } catch (error) {
    console.error("Error seeding batch 4 services:", error);
    throw error;
  }
}

seedServicesBatch4()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
